# config.py

from pathlib import Path

# --- Global Configuration (USER: Set these values) ---
BASE_WORKING_DIRECTORY = Path(r"C:\Users\Jeremy\Desktop\work\\") # <--- UPDATE THIS PATH
GCODE_FILE_NAME = "CFFFP_3DBenchy.gcode"
GCODE_FILE_PATH_STR = str(BASE_WORKING_DIRECTORY / GCODE_FILE_NAME)

PLOT_LAYER_NUMBER = 123
OUTPUT_PLOT_FILE_NAME = "infill_masked_grid_layer_123_refactored_v1.svg"
OUTPUT_PLOT_FILE_PATH_STR = str(BASE_WORKING_DIRECTORY / OUTPUT_PLOT_FILE_NAME)

PLOT_MODE = "masked_grid"
GRID_CELL_SIZE = 1.0
GRID_BOUNDS_BUFFER = 5.0

INFILL_LINE_SPACING = 0.08
INFILL_ANGLES_CYCLE = [0, 45, 90, 135]
INFILL_REGION_SHRINK_OFFSET = 0.02

X_ORDER_LEFT_TO_RIGHT = True
Y_ORDER_TOP_TO_BOTTOM = True

# --- Script Configuration (Constants) ---
RETRACTION_DISTANCE_SETTING = 6.5
RETRACTION_DETECTION_THRESHOLD_FACTOR = 0.8
ABS_E_CHANGE_FOR_RETRACTION_CMD = RETRACTION_DISTANCE_SETTING * RETRACTION_DETECTION_THRESHOLD_FACTOR
MIN_E_DELTA_FOR_PRINTING_WHEN_NOT_RETRACTED = 0.00001
COORD_EPSILON = 0.01
NODE_MERGE_EPSILON = COORD_EPSILON * 0.1
ON_SEGMENT_EPSILON = COORD_EPSILON * 3.0
ENDPOINT_DISTINCTION_EPSILON = COORD_EPSILON * 1.5

MIN_SIGNIFICANT_TRACK_LENGTH = 0.5
MIN_SIGNIFICANT_TRACK_LENGTH_SQ = MIN_SIGNIFICANT_TRACK_LENGTH**2
MIN_AREA_THRESH_FLOAT = 0.001

SMALL_DIST_FACTOR = 10
min_segment_dist_threshold = COORD_EPSILON / SMALL_DIST_FACTOR
min_segment_length_epsilon_sq = min_segment_dist_threshold**2
moved_xy_threshold = min_segment_dist_threshold / 10.0

# Add G-code generation configs here later if you proceed
ENABLE_GCODE_GENERATION = False # Placeholder
# GENERATED_GCODE_FILE_NAME = "generated_infill_layer_" + str(PLOT_LAYER_NUMBER) + ".gcode"
# GENERATED_GCODE_FILE_PATH_STR = str(BASE_WORKING_DIRECTORY / GENERATED_GCODE_FILE_NAME)
# FEEDRATE_PRIMARY_INFILL = 1800
# ... other G-code feedrates and settings